# Generated by Django 5.0 on 2026-09-28 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('work_type', models.CharField(choices=[('in-person', 'In-person'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=255)),
                ('required_skills', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('visa_sponsorship', models.BooleanField(default=False)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('removed', 'Removed')], default='active', max_length=50)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
