# Generated by Django 5.0 on 2026-09-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='salary_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary_min',
            field=models.PositiveIntegerField(),
        ),
    ]
