# Generated by Django 5.0.14 on 2026-09-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
